FuelLabs/fuel-block-committer

.github/actions/docker-publish/action.yml, .github/workflows/ci.yml
https://github.com/fuellabs/fuel-block-committer/pkgs/container/fuel-block-committer
close: #21
=> ci: add docker publish action

src/adapters/ethereum_adapter.rs, src/adapters/ethereum_adapter/monitored_adapter.rs, src/adapters/ethereum_adapter/websocket/adapter.rs, src/main.rs, src/services.rs, src/services/wallet_balance_tracker.rs, src/setup/config.rs, src/setup/helpers.rs
closes: #19 
Wallet balance will now be checked every 10s. 
Besides giving a better insight into the balance it also serves as a good heartbeat for the Ethereum connection since it will reuse the same provider over which we commit blocks.
As things currently stand, if our connection is unhealthy for 30s the service will become unhealthy.
=> feat: periodic wallet balance check

.github/workflows/ci.yml
noticed that we had several concurrent long-running jobs clogging up the runners when multiple commits were pushed to the same branch, this concurrency limit should fit that.
=> cancel previous jobs on new commits

.github/workflows/ci.yml, Cargo.toml, compose.yaml, deployment/Dockerfile, eth_node/Dockerfile, src/adapters/ethereum_adapter/monitored_adapter.rs, src/adapters/ethereum_adapter/websocket/adapter.rs, src/adapters/ethereum_adapter/websocket/event_streamer.rs, src/adapters/fuel_adapter/fuel_client.rs, src/adapters/storage/sqlite_db.rs, src/errors.rs, src/main.rs, src/services.rs, src/services/block_watcher.rs, src/services/commit_listener.rs, src/services/wallet_balance_tracker.rs, src/setup/helpers.rs, src/telemetry/health_tracker.rs
Bumped the version of the fuel core client to the latest version:
```cargo
fuel-core-client = "0.22.0"
```
Also bumped the rust version and the fuel v2 contracts repo used in the e2e tests.
=> chore: bump fuel-core version to use the latest release

compose.yaml, eth_node/Dockerfile, eth_node/hardhat.config.ts, eth_node/run.sh
fuel v2 contracts have been archived for some time. The e2e test of the committer will now use the contracts from the `fuel-bridge` repository.
=> chore: update e2e tests to use the contracts from the `fuel-bridge` repo

.github/workflows/ci.yml, Cargo.toml, compose.yaml, deployment/Dockerfile, src/adapters/fuel_adapter/fuel_client.rs
Had to disable 2 integration tests checking whether we can communicate with fuel-core's API because `fuels-rs` hasn't had a release yet.
The same functionality is covered at a higher level with the `e2e` test so I'd say we're in the clear since the e2e test passes.
Once `fuels-rs` gets a release we can come back and uncomment the tests.
=> feat: support fuel-core 0.24.1

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, compose.yaml, eth_node/Dockerfile
Support for `fuel-core` `0.25.2`.
=> chore: bump fuel core version

Cargo.lock, Cargo.toml, deployment/charts/Chart.yaml
It seems the version wasn't bumped for the `0.2.0` release. Bumping it now to `0.3.0`.
=> chore: bump versions

Cargo.lock, Cargo.toml, compose.yaml, deployment/charts/Chart.yaml, eth_node/Dockerfile, fuel-toolchain.toml
Fuel core version bumped.
Also bumped the version of the committer to `0.4.0` to prepare for the release after this PR gets merged.
=> chore: bump fuel core to 0.26.0

committer/src/config.rs, committer/src/main.rs, committer/src/setup.rs, configurations/development/config.toml, e2e/src/lib.rs, eth_node/Dockerfile, packages/eth/src/lib.rs, packages/eth/src/websocket.rs, packages/eth/src/websocket/connection.rs, packages/eth/src/websocket/health_tracking_middleware.rs, packages/ports/src/ports/l1.rs, packages/services/src/block_committer.rs
I've removed the commit_interval from our configuration. Instead, the committee will now use the interval set in the state contract directly.
- Added `BLOCKS_PER_COMMIT_INTERVAL() external view returns (uint256)` function to retrieve the commit interval from the contract.
- Extended the Contract trait with fn `commit_interval(&self) -> Result<std::num::NonZeroU32>`.
- Updated code to utilize the new `commit_interval` function.
- Added setters to the `Config` structure.
=> Pull commit interval config from contract

.github/workflows/ci.yml, committer/src/errors.rs, committer/src/main.rs
The top level errors don't have context. Difficult to tell what failed. 
The runners are fine, they are given context by the runnable.
=> refactor: add context to errors

helm/fuel-block-committer/Chart.yaml, helm/fuel-block-committer/templates/servicemonitor.yaml
closes: #119 
No metrics since the wrong endpoint was configured in the helm charts.
=> bug: fix metrics endpoint

.github/workflows/ci.yml, Cargo.lock, packages/encoding/Cargo.toml
We now check the crates we publish in isolation from the workspace and with all possible feature flag combinations.
=> chore: add cargo hack to CI for feature combinations check

packages/encoding/Cargo.toml
Even the dry running of a release doesn't catch the issue that crates.io will reject the package if it doesn't have the description set.
=> bug: add description for package

committer/src/main.rs, e2e/src/lib.rs
Temporary disable pruner until https://github.com/FuelLabs/fuel-block-committer/issues/173 is resolved
=> chore: disable pruner

.sqlx/query-39d3fae6fdd67a2324fae4d5e828f69f2298cd5b0f7eb1609ed189269c6f677c.json, committer/src/api.rs, e2e/src/committer.rs, packages/adapters/storage/src/lib.rs, packages/adapters/storage/src/postgres.rs, packages/adapters/storage/src/test_instance.rs, packages/services/src/cost_reporter.rs
Extends the costs api to support fetching the latest cost entries
BREAKING CHANGE: new query parameter needs to be specified `variant = specific | latest `
=> feat!: get latest costs from api

packages/encoding/Cargo.toml
this was preventing the crate from compiling in risc0/sp1
=> fix(fuel-block-committer-encoding): make c-kzg dependency optional

fuel_simulator/src/main.rs, fuel_simulator/src/server.rs
Simple fix for the `fuel-simulator` for running integration tests. we ensure here that we don't have uncontrolled growth in memory. the blocks vec now holds a maximum of 10_000 blocks, so the max memory usage of this structure at peak is `(10_000 * (128 + 28 + 4)) = 1.6 mb`. (with the default block size set to 128 bytes)
=> fix: uncontrolled block memory growth fuel-simulator

packages/adapters/signers/src/eigen.rs, packages/adapters/signers/src/eigen/kms.rs, packages/adapters/signers/src/eth.rs, packages/adapters/signers/src/kms_utils.rs
fixes the unnecessary casts and cleans up the module. it also has dedicated error handling now
ai generated desc:
Key changes include replacing `anyhow` errors with a custom `Error` type, improving KMS integration, and adding conditional compilation for test helpers.
* [`packages/adapters/signers/src/eigen/kms.rs`](diffhunk://#diff-6c5f639903971e7c817428d302e0ec1e3a2385a2dd4620364577d074f39c06aaL1-L216): Replaced `anyhow` errors with a custom `Error` enum to provide more granular and descriptive error handling for KMS operations. This includes errors for missing keys, invalid DER formats, and recovery ID issues.
* [`packages/adapters/signers/src/eigen.rs`](diffhunk://#diff-bc982a95fa96b121cae105051a60f994a44a6cb7dd25d1e696d4b37876bba399L24-R27): Simplified error handling in …
=> fix: eigen kms mod

committer/src/config.rs
serde annotation for `DaLayer` cfg. we will perhaps need this on `EigenDaConfig` later, but i don't see a use for it now
=> fix: serde annotation

committer/src/setup.rs
i double checked, i don't understand this todo. the metric "matches the name"
=> fix: remove todos for metrics

packages/services/src/block_bundler/eigen_bundler.rs
fixes https://github.com/FuelLabs/fuel-block-committer/pull/187#discussion_r2126570434
The most important changes include updating the logic for calculating `unused_bytes` and `total_bytes` in fragments and adding specific assertions for the last fragment in the test suite.
* Updated the calculation of `unused_bytes` to reflect the difference between the `fragment_size` and the actual chunk length. Changed `total_bytes` to dynamically use the chunk length instead of the fixed `fragment_size`. (`packages/services/src/block_bundler/eigen_bundler.rs`, [packages/services/src/block_bundler/eigen_bundler.rsL106-R107](diffhunk://#diff-f00075c135b4fe4e11a1030e50b6602a1b48bdf568d49053d27d19a30cd4b551L106-R107))
* Modified the test suite to include separate assertions for the last fragment, …
=> fix(eigen_bundler): unused bytes and total bytes calculation

.github/workflows/ci.yml, e2e/helpers/src/bin/start_committer.rs
now that we have the `EIGEN_KEY` setup in ci, we can use it in the eigen committer e2e harness
=> fix: e2e eigen committer uses EIGEN_KEY from env

packages/adapters/eigenda/src/connector.rs, packages/services/src/state_committer/eigen_service.rs, packages/services/src/state_committer/port.rs
Since our agreement with eigen is purely on the basis of the throughput, we don't need to perform any additional calculations. the condition for submitting a state fragment is purely decided by how much data we have been posting, and by re-using the `RateLimiter` on `EigenDAClient`, we can quickly check if we are exceeding that throughput. 
we also perform an additional check on the call frequency to keep that in check. other than these 2, i cannot think of any other reasons we should throttle blob submission, since we don't have to check for wallet balance or anything else
=> chore(eigen_service): allow checking if the bundle can be submitted

Cargo.lock, README.md, committer/Cargo.toml, committer/src/config.rs, committer/src/setup.rs, e2e/tests/tests/eigen_kms.rs, packages/adapters/eigenda/Cargo.toml, packages/adapters/eigenda/src/connector.rs
updates the readme with the new config params. fixes the throughput config since we expect bytes/sec. made cert verifier configurable, along with the eth rpc url. this is separate from the committer_eth_rpc because eigen v2 is on holesky.
removed the test in `eigen_kms.rs` which duplicates the test that already exists in `eigen_state.rs`. it performs the same checks
=> chore: fix config, add additional params
